-- ODEV 1
-- SELECT title, description FROM film;
-- SELECT * FROM film where length >60 and length <75;
-- SELECT * FROM film where rental_rate=0.99 and replacement_cost=12.99 or replacement_cost=28.99; 
-- SELECT first_name, last_name FROM customer where first_name='Mary'; 
-- SELECT * FROM film where not (length>50 and (rental_rate=2.99 or rental_rate=4.99));